apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector: 
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      name: demo-tmpl
      labels:
        app: demo
        "app.kubernetes.io/name": demo
        "app.kubernetes.io/instance": demo
    spec:
      containers:
        - name: demo
          image: docker.io/library/demo-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: http
